### PR TITLE
Test terraform config

### PR DESCRIPTION
**Pull request by deyanstoyanov10**

### CODE REVIEW

**Comment by deyanstoyanov10** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'apply_requirements' key: server-side config needs 'allowed_overrides: [apply_requirements]'
```

**Comment by deyanstoyanov10** [comment]
**Plan Error**
```
parsing atlantis.yaml: yaml: unmarshal errors:
  line 5: field allowed_overrides not found in type raw.Project
```

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `kafka/test` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.test_topic_module_1.kafka_topic.topicConfig will be created
+ resource "kafka_topic" "topicConfig" {
      + id                 = (known after apply)
      + name               = "messages"
      + partitions         = 5
      + replication_factor = 3
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d kafka/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-0:4141/lock?id=deyanstoyanov10%252Fkafka-terraform%252Fkafka%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d kafka/test`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by deyanstoyanov10** [comment]
atlantis apply

**Comment by deyanstoyanov10** [comment]
Ran Apply for dir: `kafka/test` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by PlatformCIBuilder — APPROVED** [review]

**Comment by deyanstoyanov10** [comment]
atlantis apply

**Comment by deyanstoyanov10** [comment]
Ran Apply for dir: `kafka/test` workspace: `default`

```diff
module.test_topic_module_1.kafka_topic.topicConfig: Creating...
module.test_topic_module_1.kafka_topic.topicConfig: Creation complete after 1s [id=messages]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by deyanstoyanov10** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `kafka/test` workspace: `default`

**Pull request merged**
